openapi: 3.0.3
info:
  title: Programer API
  version: 1.0.0
  description: A simple interfaz to register programmers
paths:
  /api/v1/programmers/:
    get:
      operationId: api_v1_programmers_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Programer'
          description: ''
    post:
      operationId: api_v1_programmers_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Programer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Programer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Programer'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Programer'
          description: ''
  /api/v1/programmers/{id}/:
    get:
      operationId: api_v1_programmers_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this programmer.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Programer'
          description: ''
    put:
      operationId: api_v1_programmers_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this programmer.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Programer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Programer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Programer'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Programer'
          description: ''
    patch:
      operationId: api_v1_programmers_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this programmer.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProgramer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedProgramer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedProgramer'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Programer'
          description: ''
    delete:
      operationId: api_v1_programmers_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this programmer.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    PatchedProgramer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        fullname:
          type: string
          maxLength: 100
        nickname:
          type: string
          maxLength: 50
        age:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
        is_active:
          type: boolean
    Programer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        fullname:
          type: string
          maxLength: 100
        nickname:
          type: string
          maxLength: 50
        age:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
        is_active:
          type: boolean
      required:
      - age
      - fullname
      - id
      - nickname
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
